name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Create test file
      run: |
          touch ./TestAPI/data.xml
          echo API_START="<?xml version="1.0" encoding="utf-8"?><wot><apiKey>" >> ./TestAPI/data.xml
          echo API_KEY=${{ secrets.TEST_WARGAMING_API }} >> ./TestAPI/data.xml
          echo API_END="</apiKey></wot>"
          ls ./TestAPI/
    - name: Test
      run: dotnet test --no-build --verbosity normal
